version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: on-failure
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: on-failure